# python train_net.py --config-file configs/semantic/eval.yaml  --num-gpus 8 --eval-only

_BASE_: ./train_semantic_large.yaml
MODEL:
  BACKBONE:
    NAME: "PEEncoder"
  META_ARCHITECTURE: "MAFT_Plus"


DATASETS:
  # TEST: ("openvocab_pascal20_sem_seg_val", "openvocab_ade20k_full_sem_seg_val", 'openvocab_pascal_ctx459_sem_seg_val', 'openvocab_pascal_ctx59_sem_seg_val', 'openvocab_ade20k_panoptic_val') 
  TEST: ( 'openvocab_ade20k_panoptic_val',)

OUTPUT_DIR: ./out/semantic/evaluation

PE:
  ENABLED: True
  MODEL_NAME: "PE-Core-L14-336"